/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * CreateWindow1.java
 *
 * Created on 19 Mar, 2012, 11:25:53 AM
 */
package videoconferencing;

import java.awt.event.KeyEvent;
import java.net.DatagramSocket;
import java.net.SocketException;
import java.util.Random;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFrame;
import videoconferencing.alpha.DBOperations;

/**
 *
 * @author Simran
 */
public class CreateWindow1 extends javax.swing.JFrame {
    
    private int textport;
    private int sendport;
    int i,k=0;
    /** Creates new form CreateWindow1 */
    public CreateWindow1() {
        initComponents();
        k=k+1;
        setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
        textport=new DBOperations().getmytextport();
        sendport=showUsers.guesttextport;
        //new DBOperations().setmytextport();
        System.out.println("receive at"+textport);
        System.out.println("send to"+sendport);
        new DBOperations().getconnection();
        /*if(k==1)
        {
          i=JOptionPane.showConfirmDialog(MainFrame.container,"Do you want to connect to "+showUsers.otherun,"Connection Confirmation",JOptionPane.YES_NO_OPTION,JOptionPane.INFORMATION_MESSAGE);
         if(i==1)
           {
          return;
            }
    //else
    //new DBOperations().setmytextport();
        }*/
        Thread t=new CreateClientTextChat(textport,sendport);
       t.start();
        try {
            Random rand=new Random();
            int k=rand.nextInt(65535-49152+1)+49152;
             CreateClientTextChat.ds4 = new DatagramSocket(k);
        } catch (SocketException ex) {
            Logger.getLogger(CreateWindow1.class.getName()).log(Level.SEVERE, null, ex);
        }
        try {
            CreateClientTextChat.TheServer();
        } catch (Exception ex) {
            Logger.getLogger(CreateWindow1.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
    
    public CreateWindow1(int i,int j)
    {
        textport=i;
        sendport=j;
        initComponents();
        setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
         System.out.println("receive at"+textport);
        System.out.println("send to"+sendport);
         Thread t=new CreateClientTextChat(textport,sendport);
        t.start();
        try {
            Random rand=new Random();
            int k=rand.nextInt(65535-49152+1)+49152;
             CreateClientTextChat.ds4 = new DatagramSocket(k);
        } catch (SocketException ex) {
            Logger.getLogger(CreateWindow1.class.getName()).log(Level.SEVERE, null, ex);
        }
        try {
            CreateClientTextChat.TheServer();
        } catch (Exception ex) {
            Logger.getLogger(CreateWindow1.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        btnStop = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        btnSend = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtSend = new javax.swing.JTextArea();
        txtMsg = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        btnStop.setText("Close");
        btnStop.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnStopActionPerformed(evt);
            }
        });
        btnStop.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                btnStopKeyPressed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 18));
        jLabel1.setText("Chat Screen");

        btnSend.setText("Send");
        btnSend.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSendActionPerformed(evt);
            }
        });
        btnSend.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                btnSendKeyPressed(evt);
            }
        });

        txtSend.setColumns(20);
        txtSend.setEditable(false);
        txtSend.setLineWrap(true);
        txtSend.setRows(5);
        txtSend.setWrapStyleWord(true);
        txtSend.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtSendMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(txtSend);

        txtMsg.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                txtMsgMousePressed(evt);
            }
        });

        jLabel2.setText("Enter text here");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(109, 109, 109)
                .addComponent(jLabel1)
                .addContainerGap(117, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addContainerGap())
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addComponent(txtMsg, javax.swing.GroupLayout.DEFAULT_SIZE, 282, Short.MAX_VALUE)
                            .addContainerGap())
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addGap(22, 22, 22)
                                    .addComponent(btnSend, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 65, Short.MAX_VALUE)
                                    .addComponent(btnStop, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(12, 12, 12))
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 259, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGap(33, 33, 33)))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(15, 15, 15)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtMsg, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnSend)
                    .addComponent(btnStop))
                .addContainerGap(23, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 335, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 7, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 6, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 283, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 8, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 7, Short.MAX_VALUE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnStopActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnStopActionPerformed
        this.dispose();
    }
        // TODO add your handling code here:         this.setVisible(false);         //System.exit(0);}//GEN-LAST:event_btnStopActionPerformed

        private void btnSendActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSendActionPerformed

        try {             // TODO add your handling code here:             txtSend.append(LoginFrame.un + ": " + txtMsg.getText() + "\r\n");             CreateClientTextChat.TheServer();             txtMsg.setText("");         } catch (Exception ex) {             Logger.getLogger(CreateWindow.class.getName()).log(Level.SEVERE, null, ex);         }     }//GEN-LAST:event_btnSendActionPerformed

            // TODO add your handling code here:
            txtSend.append(LoginFrame.un+": "+txtMsg.getText()+"\r\n");
            CreateClientTextChat.TheServer();
            txtMsg.setText("");
        } catch (Exception ex) {
            Logger.getLogger(CreateWindow1.class.getName()).log(Level.SEVERE, null, ex);
        }
        }
            
        private void txtSendMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtSendMouseClicked
        }
        // TODO add your handling code here:         //txtSend.setText("");}//GEN-LAST:event_txtSendMouseClicked

        private void txtMsgMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtMsgMousePressed
        }
        // TODO add your handling code here:         //txtMsg.setText("");}//GEN-LAST:event_txtMsgMousePressed

    private void btnSendKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_btnSendKeyPressed
        // TODO add your handling code here:
        if(evt.getKeyCode()== KeyEvent.VK_ENTER)
        {
            try {             // TODO add your handling code here:             txtSend.append(LoginFrame.un + ": " + txtMsg.getText() + "\r\n");             CreateClientTextChat.TheServer();             txtMsg.setText("");         } catch (Exception ex) {             Logger.getLogger(CreateWindow.class.getName()).log(Level.SEVERE, null, ex);         }     }                                       

            // TODO add your handling code here:
            txtSend.append(LoginFrame.un+": "+txtMsg.getText()+"\r\n");
            CreateClientTextChat.TheServer();
            txtMsg.setText("");
        } catch (Exception ex) {
            Logger.getLogger(CreateWindow1.class.getName()).log(Level.SEVERE, null, ex);
        }
        }
    }//GEN-LAST:event_btnSendKeyPressed

    private void btnStopKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_btnStopKeyPressed
        // TODO add your handling code here:
        if(evt.getKeyCode()== KeyEvent.VK_ENTER)
            this.dispose();
    }//GEN-LAST:event_btnStopKeyPressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CreateWindow1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CreateWindow1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CreateWindow1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CreateWindow1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                new CreateWindow1().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnSend;
    private javax.swing.JButton btnStop;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    public static javax.swing.JTextField txtMsg;
    public static javax.swing.JTextArea txtSend;
    // End of variables declaration//GEN-END:variables
}
