/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * MainFrame.java
 *
 * Created on 16 Jan, 2012, 4:24:04 PM
 */
package videoconferencing;

import Whiteboarding.main.Server;
import java.awt.Container;
import java.awt.Toolkit;
import java.io.File;
import java.util.ArrayList;
import javax.swing.JFileChooser;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import videoconferencing.alpha.DBOperations;

/**
 *
 * @author Simran
 */
public class MainFrame extends javax.swing.JFrame {
    DBOperations db = new DBOperations();
    public static Container container;
        
    /** Creates new form MainFrame */
    public MainFrame() {
        initComponents(); 
        setDefaultCloseOperation(JFrame.DO_NOTHING_ON_CLOSE);
        pnlAbout.setVisible(false);
        setSize(Toolkit.getDefaultToolkit().getScreenSize());
        
        container = getContentPane();
        //this.add(pnlAbout,BorderLayout.CENTER);
        db.setIP();
        db.setReceivePort();
        FileServer.port=db.getfileport();
       Thread t=new Socketserver();
       t.start();
       Thread tt=new SocketserverVideo();
       tt.start();
  }

    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlAbout = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        mnuFile = new javax.swing.JMenu();
        jMenuItem4 = new javax.swing.JMenuItem();
        jMenuItem1 = new javax.swing.JMenuItem();
        mnuUserMaintenance = new javax.swing.JMenu();
        jMenuItem5 = new javax.swing.JMenuItem();
        jMenuItem8 = new javax.swing.JMenuItem();
        mnuStream = new javax.swing.JMenu();
        jMenuItem2 = new javax.swing.JMenuItem();
        jMenuItem3 = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        jMenuItem9 = new javax.swing.JMenuItem();
        jMenuItem10 = new javax.swing.JMenuItem();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem6 = new javax.swing.JMenuItem();
        jMenuItem7 = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        pnlAbout.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(204, 153, 0)));
        pnlAbout.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        jLabel1.setText("This Project is Developed by");

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 12));
        jLabel2.setText("Simrandeep Singh");

        jLabel3.setText("Pre Final year Student of Thapar University");

        jLabel4.setText("Computer Science and Engineering Department");

        jLabel5.setText("Roll No. - 100903105");

        jLabel6.setText("At");

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 12));
        jLabel7.setText("AT&T Communication Services India Pvt. Ltd.");

        jLabel8.setText("Gurgaon, Haryana (India).");

        jButton1.setText("OK");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnlAboutLayout = new javax.swing.GroupLayout(pnlAbout);
        pnlAbout.setLayout(pnlAboutLayout);
        pnlAboutLayout.setHorizontalGroup(
            pnlAboutLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlAboutLayout.createSequentialGroup()
                .addContainerGap(50, Short.MAX_VALUE)
                .addComponent(jLabel3)
                .addGap(39, 39, 39))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlAboutLayout.createSequentialGroup()
                .addContainerGap(40, Short.MAX_VALUE)
                .addComponent(jLabel4)
                .addGap(31, 31, 31))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlAboutLayout.createSequentialGroup()
                .addContainerGap(144, Short.MAX_VALUE)
                .addComponent(jLabel6)
                .addGap(142, 142, 142))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlAboutLayout.createSequentialGroup()
                .addContainerGap(89, Short.MAX_VALUE)
                .addComponent(jLabel8)
                .addGap(80, 80, 80))
            .addGroup(pnlAboutLayout.createSequentialGroup()
                .addGap(121, 121, 121)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(121, Short.MAX_VALUE))
            .addGroup(pnlAboutLayout.createSequentialGroup()
                .addGap(81, 81, 81)
                .addComponent(jLabel1)
                .addContainerGap(81, Short.MAX_VALUE))
            .addGroup(pnlAboutLayout.createSequentialGroup()
                .addGap(92, 92, 92)
                .addGroup(pnlAboutLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlAboutLayout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(jLabel5))
                    .addComponent(jLabel2))
                .addContainerGap(94, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlAboutLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel7)
                .addContainerGap())
        );
        pnlAboutLayout.setVerticalGroup(
            pnlAboutLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlAboutLayout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel8)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButton1)
                .addContainerGap(20, Short.MAX_VALUE))
        );

        mnuFile.setText("File");

        jMenuItem4.setText("Change Password");
        jMenuItem4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem4ActionPerformed(evt);
            }
        });
        mnuFile.add(jMenuItem4);

        jMenuItem1.setText("Logout");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        mnuFile.add(jMenuItem1);

        jMenuBar1.add(mnuFile);

        mnuUserMaintenance.setText("User Account");

        jMenuItem5.setText("Profile Personal Detail");
        jMenuItem5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem5ActionPerformed(evt);
            }
        });
        mnuUserMaintenance.add(jMenuItem5);

        jMenuItem8.setText("Upload File for Video User");
        jMenuItem8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem8ActionPerformed(evt);
            }
        });
        mnuUserMaintenance.add(jMenuItem8);

        jMenuBar1.add(mnuUserMaintenance);

        mnuStream.setText("User Connection");

        jMenuItem2.setText("Text Connection");
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2ActionPerformed(evt);
            }
        });
        mnuStream.add(jMenuItem2);

        jMenuItem3.setText("VideoConferencing Connection");
        jMenuItem3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem3ActionPerformed(evt);
            }
        });
        mnuStream.add(jMenuItem3);

        jMenuBar1.add(mnuStream);

        jMenu2.setText("WhiteBoarding");

        jMenuItem9.setText("Start Session");
        jMenuItem9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem9ActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem9);

        jMenuItem10.setText("Join Session");
        jMenuItem10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem10ActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem10);

        jMenuBar1.add(jMenu2);

        jMenu1.setText("Help");

        jMenuItem6.setText("Contact Admin");
        jMenuItem6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem6ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem6);

        jMenuItem7.setText("About");
        jMenuItem7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem7ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem7);

        jMenuBar1.add(jMenu1);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(163, 163, 163)
                .addComponent(pnlAbout, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(128, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(76, 76, 76)
                .addComponent(pnlAbout, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(73, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
/*        try {
            // TODO add your handling code here:
            new ShowMyVideoMedia_andReceiveVideo();
        }
        catch(Exception e)
        {
        e.printStackTrace();
        }*/
        db.setStatus(LoginFrame.un,0);
        System.exit(0);
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed
        db.setChatStatus(LoginFrame.un,"t");
        ArrayList al = db.getUsers("t");
        
        container.removeAll();
        showUsers su=new showUsers();
        su.setBounds(350,100, 642, 485);
        container.setVisible(false);
        container.add(su);
        container.setVisible(true);
        su.showMails(al,"t");
      /*  try {
            db.createClient();
        } catch (Exception ex) {
            Logger.getLogger(MainFrame.class.getName()).log(Level.SEVERE, null, ex);
        }*/
    }//GEN-LAST:event_jMenuItem2ActionPerformed

    private void jMenuItem3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem3ActionPerformed
               
        db.setChatStatus(LoginFrame.un,"v");
        ArrayList al = db.getUsers("v");
         
         container.removeAll();
         showUsers su=new showUsers();
         su.setBounds(350,100, 642, 485);
         container.setVisible(false);
        container.add(su);
        container.setVisible(true);
        su.showMails(al,"v");
    }//GEN-LAST:event_jMenuItem3ActionPerformed

    private void jMenuItem4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem4ActionPerformed
        // TODO add your handling code here:
        new ChangePassword().setVisible(true);
        //this.dispose();
    }//GEN-LAST:event_jMenuItem4ActionPerformed

    private void jMenuItem5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem5ActionPerformed
        // TODO add your handling code here:
        container.removeAll();
        ProfilePersonalDetail obj=new ProfilePersonalDetail();
        obj.setBounds(370,50,600, 600);
        container.add(obj);
        container.setVisible(false);
        container.setVisible(true);
    }//GEN-LAST:event_jMenuItem5ActionPerformed

    private void jMenuItem6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem6ActionPerformed
        // TODO add your handling code here:
        ConfirmPassword.email=new DBOperations().getEmailfromUserName();
        if(ConfirmPassword.email==null)
        {
            JOptionPane.showMessageDialog(this,"Update Your Email-id","Error",2);
             return;
        }
        else
        {
            ConfirmPassword c=new ConfirmPassword();
            c.setVisible(true);
        }
    }//GEN-LAST:event_jMenuItem6ActionPerformed

    private void jMenuItem7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem7ActionPerformed
        // TODO add your handling code here:
        container.removeAll();
         pnlAbout.setBounds(500,180, 315, 260);
         container.setVisible(false);
        container.add(pnlAbout);
        container.setVisible(true);
       pnlAbout.setVisible(true);
    }//GEN-LAST:event_jMenuItem7ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed

        // TODO add your handling code here:         pnlAbout.setVisible(false);     }//GEN-LAST:event_jButton1ActionPerformed
/*
        private void jMenuItem8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem8ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuItem8ActionPerformed

        private void jMenuItem9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem9ActionPerformed
      
        }//GEN-LAST:event_jMenuItem9ActionPerformed

        private void jMenuItem10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem10ActionPerformed
        
        }//GEN-LAST:event_jMenuItem10ActionPerformed
     */   pnlAbout.setVisible(false);
    }
    private void jMenuItem9ActionPerformed(java.awt.event.ActionEvent evt) {
        // TODO add your handling code here:
        //SessionBrowserServer.BASE_PORT+=2;
        Thread t=new Server();
        t.start();
        }
        private void jMenuItem10ActionPerformed(java.awt.event.ActionEvent evt) {
            ArrayList al=db.getloggedinusers();
            new showServers(al);
       // String[] arg = {"-c"};
        // TODO add your handling code here:
         //   Jinn.main(arg);
        }

     private void jMenuItem8ActionPerformed(java.awt.event.ActionEvent evt) {
                                        JFileChooser fc = new JFileChooser();
                                        int returnVal=fc.showOpenDialog(this);
                                        if (returnVal == javax.swing.JFileChooser.APPROVE_OPTION) {
                                        //String filename=fc.getSelectedFile().getName();
                                         String name=fc.getSelectedFile().getName();
                                        FileServer.filename=fc.getSelectedFile().getPath();
                                        File files = fc.getSelectedFile();
                                        String ext=fc.getSelectedFile().getName();
                                        ext=ext.substring(ext.length()-4);
                                        System.out.println(ext);
                                        if(ext.equalsIgnoreCase(".exe"))
                                        {
                                             JOptionPane.showMessageDialog(MainFrame.container,".exe file not allowed.","Warning",JOptionPane.OK_OPTION);
                                             return;
                                        }
                                        FileServer.port=FileServer.port+2;
                                        int port=FileServer.port;
                                        //byte [] mybytearray  = new byte [(int)FileServer.filename.length()];
                                        //System.out.println(FileServer.filename.length());
                                        //System.out.println(mybytearray.length);
                                        //System.out.println(files.getTotalSpace());
                                        int fileSize = (int) files.length();
                                        System.out.println(fileSize);
                                        if(fileSize>5276270)
                                        {
                                             JOptionPane.showMessageDialog(MainFrame.container,"File size should not be greater than 5 MB.","Warning",JOptionPane.OK_OPTION);
                                             return;
                                        }
                                        else
                                        {
                                        Thread t= new FileServer();
                                        t.start();
                                        db.setfilename(name,port);
                                        }
                                        //System.out.println(filename+" and "+path);
                                        }
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                new MainFrame().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem10;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JMenuItem jMenuItem4;
    private javax.swing.JMenuItem jMenuItem5;
    private javax.swing.JMenuItem jMenuItem6;
    private javax.swing.JMenuItem jMenuItem7;
    private javax.swing.JMenuItem jMenuItem8;
    private javax.swing.JMenuItem jMenuItem9;
    private javax.swing.JMenu mnuFile;
    private javax.swing.JMenu mnuStream;
    private javax.swing.JMenu mnuUserMaintenance;
    private javax.swing.JPanel pnlAbout;
    // End of variables declaration//GEN-END:variables

    
}
