/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * SignUp.java
 *
 * Created on 27 Feb, 2012, 11:31:45 AM
 */
package videoconferencing;

import javax.swing.JFrame;
import javax.swing.JOptionPane;
import videoconferencing.alpha.DBOperations;

/**
 *
 * @author Simran
 */
public class SignUp extends javax.swing.JFrame {
    
    DBOperations db=new DBOperations();

    /** Creates new form SignUp */
    public SignUp() {
        initComponents();
        setLocationRelativeTo(null);
        setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        txtUserName = new javax.swing.JTextField();
        txtPassword = new javax.swing.JPasswordField();
        txtConfirmPassword = new javax.swing.JPasswordField();
        txtEmailId = new javax.swing.JTextField();
        btnRegister = new javax.swing.JButton();
        btnCancel = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18));
        jLabel1.setText("Sign Up");

        jLabel2.setText("UserName");

        jLabel3.setText("Password");

        jLabel4.setText("Confirm Password");

        jLabel5.setText("Email-Id");

        btnRegister.setText("Register");
        btnRegister.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegisterActionPerformed(evt);
            }
        });

        btnCancel.setText("Cancel");
        btnCancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelActionPerformed(evt);
            }
        });

        jLabel6.setText("(Gmail Account)");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(192, 192, 192)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(61, 61, 61)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel3)
                            .addComponent(jLabel2)
                            .addComponent(jLabel4)
                            .addComponent(jLabel5))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 54, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtEmailId)
                            .addComponent(txtConfirmPassword)
                            .addComponent(txtPassword)
                            .addComponent(txtUserName, javax.swing.GroupLayout.DEFAULT_SIZE, 145, Short.MAX_VALUE))))
                .addGap(18, 18, 18)
                .addComponent(jLabel6)
                .addGap(29, 29, 29))
            .addGroup(layout.createSequentialGroup()
                .addGap(118, 118, 118)
                .addComponent(btnRegister)
                .addGap(69, 69, 69)
                .addComponent(btnCancel, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(133, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(jLabel1)
                .addGap(66, 66, 66)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtUserName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(37, 37, 37)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txtPassword, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(34, 34, 34)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(txtConfirmPassword, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(34, 34, 34)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(txtEmailId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 46, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnCancel)
                    .addComponent(btnRegister))
                .addGap(61, 61, 61))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnCancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelActionPerformed
        // TODO add your handling code here:
        new LoginFrame().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnCancelActionPerformed

    private void btnRegisterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegisterActionPerformed
        // TODO add your handling code here:
        String username=txtUserName.getText();
        Boolean un=db.checkUsername(username);
        String pw=new String(txtPassword.getPassword());
        String cpw=new String(txtConfirmPassword.getPassword());
        for(int i=0;i<username.length();i++)
        {
            if(!((username.codePointAt(i)>=65 && username.codePointAt(i)<=90)||(username.codePointAt(i)>=97 && username.codePointAt(i)<=122)||(username.codePointAt(i)>=48 && username.codePointAt(i)<=57)))
            {
            JOptionPane.showMessageDialog(this,"Special Characters in Username not Allowed","SignUp",JOptionPane.WARNING_MESSAGE);
            return;
            }   
        }
        if(un==true)
        {
            JOptionPane.showMessageDialog(this,"Username already exists","SignUp",JOptionPane.WARNING_MESSAGE);
            return;
        }
        else if("".equals(username))
        {
            JOptionPane.showMessageDialog(this,"Enter Username","SignUp",JOptionPane.WARNING_MESSAGE);
            return;
        }
        if("".equals(pw))
        {
            JOptionPane.showMessageDialog(this,"Enter Password","SignUp",JOptionPane.WARNING_MESSAGE);
            return;
        }
        else if(pw.length()<6)
        {
            JOptionPane.showMessageDialog(this,"Password Should Be minimum 6 digits","SignUp",JOptionPane.WARNING_MESSAGE);
            return;
        }
        if(!(pw.equals(cpw)))
        {
            JOptionPane.showMessageDialog(this,"Password and Confirm Password Should match","SignUp",JOptionPane.WARNING_MESSAGE);
            return;
        }
        if(!(validateEmail(txtEmailId.getText())))
        {
            JOptionPane.showMessageDialog(this,"Enter Email-Id Correctly","SignUp",JOptionPane.WARNING_MESSAGE);
            return;
        }
        int i=db.signup(username,pw,txtEmailId.getText());
        if(i>0)
        {
            JOptionPane.showMessageDialog(this,"Registered Successfully","SignUp",JOptionPane.INFORMATION_MESSAGE);
            new LoginFrame().setVisible(true);
            this.dispose();
        }
        else
        {
            JOptionPane.showMessageDialog(this,"Not Registered Successfully","SignUp",JOptionPane.INFORMATION_MESSAGE);
            new LoginFrame().setVisible(true);
            this.dispose();
        }
    }//GEN-LAST:event_btnRegisterActionPerformed

    public boolean validateEmail(String emailAddress)
    {

    // a string without a "@" is an invalid email address
        
        int index=emailAddress.indexOf("@");
    if ( index < 0 || index!=emailAddress.lastIndexOf("@"))
      return false;

    if(index==0 || index==emailAddress.length()-1)
        return false;


    String[] str=emailAddress.split("@");
    for(int i=1;i<str[0].length()-1;i++)
    {
        int j=str[0].codePointAt(i);
        if(!((j>=65 & j<=90) || (j>=97 & j<=122) || (j>=48 & j<=57)))
        {
            if(j==str[0].codePointAt(i+1))
            {
                JOptionPane.showMessageDialog(this,"Email-Id username cannot contain consective special symbols","Error",2);
                return false;
            }
        }
    }


    if(str[1].indexOf(".")<0)
    {
        JOptionPane.showMessageDialog(this,"in-correct domain name","Error",2);
        return false;
    }
    index=str[1].codePointAt(0);
    if(!(index>=97 & index<=122))
    {
        JOptionPane.showMessageDialog(this,"in-correct domain name","Error",2);
        return false;
    }
    int i=str[1].codePointAt(str[1].length()-1);
    if(!(i>=97 & i<=122))
    {
        JOptionPane.showMessageDialog(this,"in-correct domain name","Error",2);
        return false;
    }
    int k=emailAddress.indexOf("gmail.", emailAddress.indexOf("@"));
    if(k<0)
    {
        JOptionPane.showMessageDialog(this,"Only Gmail Account allowed","Error",2);
        return false;
    }
    for(i=1;i<str[1].length()-1;i++)
    {
        int j=str[1].codePointAt(i);
        if(!((j>=65 & j<=90) || (j>=97 & j<=122) || (j>=48 & j<=57)))
        {
            if(j==str[1].codePointAt(i+1))
            {
                JOptionPane.showMessageDialog(this,"in-correct domain name","Error",2);
                return false;
            }
        }
    }
    return true;
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SignUp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SignUp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SignUp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SignUp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                new SignUp().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCancel;
    private javax.swing.JButton btnRegister;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPasswordField txtConfirmPassword;
    private javax.swing.JTextField txtEmailId;
    private javax.swing.JPasswordField txtPassword;
    private javax.swing.JTextField txtUserName;
    // End of variables declaration//GEN-END:variables
}
